### ISSUE TITLE
Infinite loop in ZString.Format

### ISSUE THREAD

**Issue by itn3000** [Cysharp/ZString#1]
# Overview

Infinite loop and memory allocation error in `ZString.Format<string>()`

# Steps to reproduce

1. create console app and add project ref to ZString
2. run `ZString.Format("abcdef: {0}", "abc");`

# Expected result

get "abcdef: abc"

# Actual result

added "adef: " in loop in `Utf16ValueStringBuilder.AppendFormat<T0>` infinitely, and thrown OutOfMemoryException in `ArrayPool<T>.Rent()` finally.

**Comment by neuecc** [comment]
thanks for trying!
This is caused from refactored by FormatParser.Parse.
I've fixed.
