### ISSUE TITLE
ZString.Join() not thread safe?

### ISSUE THREAD

**Issue by dengxufan** [Cysharp/ZString#10]
It seems that concurrent calling of ZString.Join() Fails.

Call stacks:

System.ArgumentException: Can't format argument. (Parameter 'value')
at Cysharp.Text.Utf8ValueStringBuilder.ThrowArgumentException(String paramName)
at Cysharp.Text.Utf8ValueStringBuilder.Append[T](T value)
at Cysharp.Text.ZString.Join[T](String separator, T[] values)

**Comment by neuecc** [comment]
Thank you, `ZString.Join` is thread-safe.
However, there was a bug in the stretching process.
The following code will reproduce it.

```csharp
var a = new string('a', 30000);
var b = new string('b', 1000000);
ZString.Join(',', new string[] { a, b });
```

I'll fix soon.

**Comment by neuecc** [comment]
I've upload `2.1.0`, please try it.
