### ISSUE TITLE
Unittest failed

### ISSUE THREAD

**Issue by yangruihan** [Cysharp/ZString#102]
# Unittest failed

I ran the unit tests on my local mac and found 2 errors

<img width="1576" alt="image" src="https://github.com/Cysharp/ZString/assets/7806458/519ed977-8b73-44db-ad48-bff3f357da12">

<img width="1515" alt="image" src="https://github.com/Cysharp/ZString/assets/7806458/d0dbbabf-629f-4084-b4f2-fd9beba0bc46">

My enviroment:

```
> dotnet --info
.NET SDK:
 Version:   7.0.404
 Commit:    22f221a24c

运行时环境:
 OS Name:     Mac OS X
 OS Version:  14.1
 OS Platform: Darwin
 RID:         osx-arm64
 Base Path:   /usr/local/share/dotnet/sdk/7.0.404/

Host:
  Version:      7.0.14
  Architecture: arm64
  Commit:       808851b07a
```

**Comment by neuecc** [comment]
I see, because actual and expected are the same in win, linux,
Format on osx returns different results.
This subtle difference in results may be more of a dotnet/runtime issue.
If so, we cannot support it.
