### ISSUE TITLE
Is the content of LICENSE correct?

### ISSUE THREAD

**Issue by udaken** [Cysharp/ZString#25]
The ZString contains some files that are copyrighted by the .NET Foundation. Like [this files](https://github.com/Cysharp/ZString/tree/master/src/ZString/Number).

However, the LICENSE file does not mention this.

Is this the state of affairs assumed by the repository owner?

**Comment by neuecc** [comment]
aspnetcore separated LICENSE and THIRD-PARTY-NOTICES.
https://github.com/dotnet/aspnetcore/blob/master/LICENSE.txt
https://github.com/dotnet/aspnetcore/blob/master/THIRD-PARTY-NOTICES.txt

I've already mentioned at README that using, but okay, add more license info.
https://github.com/Cysharp/ZString/commit/80f2211e2e30ea0ccf155d86976eee22ddef1b4c
