### ISSUE TITLE
Support UPM

### ISSUE THREAD

**Issue by laicasaane** [Cysharp/ZString#28]
Similar to this case https://github.com/Cysharp/UniTask/issues/25, please add a `package.json` 😊

**Comment by neuecc** [comment]
can not includes external managed dlls so does not work completely.
Is that okay?

**Comment by laicasaane** [comment]
That is completely OK. External dlls should be defined in the dependencies section, then the users have to include them explicitly by either importing them into their Assets folder or using respective UPM packages. The last time I checked, `System.Buffers.dll`, `System.Memory.dll`, `System.Runtime.CompilerServices.Unsafe.dll` are all available on OpenUPM.

**Comment by neuecc** [comment]
I've added package.json.
https://github.com/Cysharp/ZString/commit/7890fa1b5970510575a6682e930f111f9ecb65bd

**Comment by laicasaane** [comment]
There should be a tag after adding package.json for it to work.
