### ISSUE TITLE
It looks like memory leak in Utf16ValueStringBuilder.Insert

### ISSUE THREAD

**Issue by martynovs** [Cysharp/ZString#36]
Original buffer is not released before assigning new buffer

https://github.com/Cysharp/ZString/blob/98379750ad4aae4c75b2ea1559d47b6931d866dc/src/ZString/Utf16ValueStringBuilder.cs#L309-L314

For example `Grow` releases buffer before assigning new one

https://github.com/Cysharp/ZString/blob/98379750ad4aae4c75b2ea1559d47b6931d866dc/src/ZString/Utf16ValueStringBuilder.cs#L139-L146

**Comment by neuecc** [comment]
thanks, fixed at 2.3.0.
