### ISSUE TITLE
FormatHelper.cs has no meta file, but it's in an immutable folder.

### ISSUE THREAD

**Issue by ewnu** [Cysharp/ZString#37]
Hello,
I've installed ZString with openupm-cli on my project.

Unfortunately, I'm stuck with an error message stating
`Asset Packages/com.cysharp.zstring/FormatHelper.cs has no meta file, but it's in an immutable folder. The asset will be ignored.`
with 410+ errors

As a workaround,
 if I manually generate .meta file by copying to other directory, then putting it back, it temporarly works until the next module refresh; the .meta file disappears.

I'm using Unity 2019.4.18 LTS.
Thanks in advance.

**Comment by neuecc** [comment]
thanks, I've added .meta and released `2.3.1`.
