### ISSUE TITLE
DLL conflicts

### ISSUE THREAD

**Issue by Kazkoo** [Cysharp/ZString#40]
Hi, I get some breaking dll errors in Unity. Seems to be an issue of conflicting DLLs with @SolidAlloy package.
Link to issue: https://github.com/SolidAlloy/ClassTypeReference-for-Unity/issues/25#issue-800264483

If you can, please check on it and provide your view on this. Thanks a lot!

**Comment by Kazkoo** [comment]
@neuecc any ideas for a solution? Thanks!

**Comment by neuecc** [comment]
I'm not familiar with SolidAlloy/ClassTypeReference-for-Unity so I have no advice.
