### ISSUE TITLE
Add assembly signing

### ISSUE THREAD

**Issue by lahma** [Cysharp/ZString#46]
Would it be possible to add assembly signing to build process and published DLL (with public snk file). Now this library cannot be referenced from signed assemblies. I believe Microsoft recommendation is to sign assemblies with publicly available key for compatibility and not security.

**Comment by neuecc** [comment]
Personally, I hate signing.
Does your application include the .NET Framework?
However, I can see the need for it, so I'll think about it.

**Comment by lahma** [comment]
Yes these are some templating projects that I'm investigating (signed) and the target both netstandard2.0 and net461. Thanks for considering the possibility.

**Comment by buybackoff** [comment]
I wanted to raise the same issue.

> I hate signing

Me too, but the full framework is here for a long time for desktop stuff. I've noticed you have [Ulid signed](https://github.com/Cysharp/Ulid/blob/master/src/Ulid/release.snk). Signing ZString and ZLogger as well will be highly appreciated.

Maybe just reusing the same key as Ulid. It always annoys me to generate a new key, google the syntax for VS console, etc. But the key doesn't matter, it could be any throwaway one.

**Comment by neuecc** [comment]
I've relased `2.4.0`, it has been signed.
I'll sign ZLogger soon.

Thanks for the requests.
