### ISSUE TITLE
Error CS0426: The type name 'CreateStringBuilder' does not exist in the type 'ZString'

### ISSUE THREAD

**Issue by MagicAndre1981** [Cysharp/ZString#48]
I tried to use your lib as [shown in the readme](https://github.com/Cysharp/ZString#getting-started) in a .Net Core 3.1 WinForms application, but I always get this error:

![error_zstring](https://user-images.githubusercontent.com/8274816/114665002-c5d9a980-9cfc-11eb-91c1-aab853488408.png)

(This first entry is to show the compiler/c# lang version for debug reasons)

I added the using statement `using Cysharp.Text;` VS shows that ZString is found, but for whatever reason it can't find `CreateStringBuilder()`.

Now I have no idea what to do. 

VS2019 16.9.4
ZString 2.4.1
.NET Core 3.1.14

**Comment by neuecc** [comment]
You're writing `var sb = **new** ZString.CreateStringBuilder()`.
The correct one: `var sb = ZString.CreateStringBuilder()`
