### ISSUE TITLE
Built-in support for TextWriter implementations

### ISSUE THREAD

**Issue by lahma** [Cysharp/ZString#49]
Currently you cannot directly use `StringWriter` with ZString as `StringWriter` accepts regular `StringBuilder`. I created helper [ZStringWriter](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Abstractions/Pooling/ZStringWriter.cs) for Orchard Core. Would it make sense to offer `ZStringWriter` (UTF-16) and `Utf8ZStringWriter` out of the box?

If you think it's a viable option I could offer a PR, just tell me desired names for the classes and namespace.

**Comment by neuecc** [comment]
`ZStringWriter` for `StringWriter`, I think it's a good and intuitive name.
The implementation is also good, I hadn't thought of that idea.

If you give me a PR, I would love to accept it.
I think we should keep the name as proposed and use the top-level namespace (`Cysharp.Text`).

**Comment by lahma** [comment]
Here's the PR for basic implementation, maybe can be improved further if specific uses and overloads are needed https://github.com/Cysharp/ZString/pull/50 .

**Comment by lahma** [comment]
@neuecc Have you happened to have time to have a glimpse at the PR? I'd love to improve if needed.

**Comment by neuecc** [comment]
I've done most of it, so yes, I'll Merge the PR first, since it's unlikely to cause breaking changes in later expansions.

**Comment by neuecc** [comment]
Sorry, I've focused to release new library [MessagePipe](https://github.com/Cysharp/MessagePipe/).
I've done most of it, so yes, I'll Merge the PR first, since it's unlikely to cause breaking changes in later expansions.

**Comment by lahma** [comment]
Thanks for accepting the PR. Your new library looks awesome, you seem to have great productivity! Eagerly waiting for release bits 😉

**Comment by neuecc** [comment]
I've released (`2.4.2`) and add description to ReadMe.
Thanks!

**Comment by lahma** [comment]
Thank you for being so reactive!
