### ISSUE TITLE
AppendFormat based on ReadOnlySpan?

### ISSUE THREAD

**Issue by mdsitton** [Cysharp/ZString#62]
Hi I have a feature request, it would be nice to have the ability to have an implementation of AppendFormat that takes a ReadOnlySpan instead of the format string that way we can pass in data from another ZStringBuilder through span as a format string.

This is useful for building a format string based on input data coming in through a function without allocating a new string for the format string.

**Comment by mdsitton** [comment]
https://github.com/mdsitton/ZString/tree/SpanFormat I've created a quick experiment of this based off of one of the other pr's to test this out.

**Comment by neuecc** [comment]
thanks, it seems good.
