### ISSUE TITLE
Unity 2021.2.0b6 breaks ZString because of System.Memory

### ISSUE THREAD

**Issue by SugoiDev** [Cysharp/ZString#63]
Unity updated its framework and now it has System.Memory, but it is not as recent.
So it doesn't have all features, and we can no longer use System.Memory.dll because it will conflict with mscorlib.

For example, using the .NET framework profile (not .NET standard):

```
ZString\FormatParser.cs(34,28): error CS0570: 'ReadOnlySpan<T>.this[int].get' is not supported by the language
ZString\Shims.cs(51,32): error CS0570: 'ReadOnlySpan<T>.GetPinnableReference()' is not supported by the language
```

**Comment by neuecc** [comment]
As posted in the Unity forum, I think this is a bug in Unity.

**Comment by azuma560** [comment]
I had the same problem
Related to this:
https://forum.unity.com/threads/2021-2-0b6-and-system-memory-readonlyspan-under-net-4-8.1152104/

**Comment by CarpetHead** [comment]
I think the actual situation is to do with the fact that unity 2021.2 natively support .net standard 2.1 API and so doesn't need the memory or buffers dlls in the unitypackage - I also think the plugin can probably be tweaked for this new environment for the better?

**Comment by neuecc** [comment]
For now, please uncheck the box when importing.
Also, the Managed DLL is not included in the installation from UPM, so it is not a problem.
