### ISSUE TITLE
Support C# 10 string interpolation

### ISSUE THREAD

**Issue by NN---** [Cysharp/ZString#65]
Together with InterpolatedStringHandler this should be even faster than before.

https://devblogs.microsoft.com/dotnet/string-interpolation-in-c-10-and-net-6/

**Comment by neuecc** [comment]
Yes, I'm interested.

**Comment by neuecc** [comment]
It will be a little better, but not ideal, so I want to pend it.
If the proposed UTF8-String-Literals supports  InterpolatedStringHandler, we can create an ideal API.
https://github.com/dotnet/csharplang/pull/5355

```csharp
// concept design.
[InterpolatedStringHandler]
public ref struct Utf8InterpolatedStringHandler
{
    IBufferWriter<byte> bufferWriter;

    public Utf8InterpolatedStringHandler(int literalLength, int formattedCount, IBufferWriter<byte> bufferWriter)
    {
        this.bufferWriter = bufferWriter;
    }

    public void AppendLiteral(ReadOnlySpan<byte> s)
    {
        s.CopyTo(bufferWriter.GetSpan(s.Length));
        bufferWriter.Advance(s.Length);
    }

    public void AppendFormatted<T>(T value)
    {
        var size = Unsafe.SizeOf<T>();
        Utf8Formatter.TryFormat(value, bufferWriter.GetSpan(size), out var written);
        bufferWriter.Advance(written);
    }
}
```

I'll make a suggestion when the utf8-string-literals discussion is started.
https://github.com/dotnet/csharplang/blob/main/proposals/utf8-string-literals.md

**Comment by NN---** [comment]
C# 11 introduces UTF-8 string literals: https://devblogs.microsoft.com/dotnet/csharp-11-preview-updates/#utf-8-string-literals

**Comment by neuecc** [comment]
Finally UTF8 type is not introduced in C#.
It seems that only `ReadOnlySpan<byte>` is available.
