### ISSUE TITLE
Compiler error on import due to dependance on TMP

### ISSUE THREAD

**Issue by popcron** [Cysharp/ZString#69]
Some of my projects dont use TMP, and zstring has a reference to TMP components. Is there a way this dependance can be omitted depending on whether TMP is actually in the project or not?

**Comment by neuecc** [comment]
Thank you.
I will have to fix the asmdef.
I will fix it.

**Comment by neuecc** [comment]
A little consideration needs to be given to the balance with the existing ones.

**Comment by popcron** [comment]
created a pr to resolve this [here](https://github.com/Cysharp/ZString/pull/75)

**Comment by popcron** [comment]
bumping it to keep this open because i believe it should be split, do you have an explanation/reasoning for why not @neuecc ?

> I don't agree with putting it in Sample.
