### ISSUE TITLE
Unity 2021.3.2f1 is getting over 1kb of gc collection from zstring

### ISSUE THREAD

**Issue by SeanMurphy2k17** [Cysharp/ZString#76]
Hello,

I've recently had to update to the unity 2021.3.2f1 and when using ZString.format i'm getting a lot of GC collection calls now. Is this a known issue? Sometimes up to multiple kb of gc. Is this an easy way to fix this?

Thanks, have a good day.

**Comment by neuecc** [comment]
Thanks for the reporting.
Could you provide reproduce code and image of profiling result?
