### ISSUE TITLE
Huge amounts of GC when appending floats

### ISSUE THREAD

**Issue by CarpetHead** [Cysharp/ZString#97]
![image](https://github.com/Cysharp/ZString/assets/7747065/99973c23-0123-4685-bb31-1d314b3c963f)
Here's a profiler image of the issue. We are essentially just appending floating point numbers (part of a vector) - we're using unity 2022.3.11f1

is this expected behaviour? is there any way to avoid this?

**Comment by kochounoyume** [comment]
Here, if we can get some more implementation details, we may be on to something.

I could not see this behavior in my environment.
